dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
services:
- docker
- xvfb
addons:
  chrome: stable
env:
  global:
    - ENVIRONMENT=ci
    - BASE_FOLDER=$TRAVIS_BUILD_DIR
    - WEB_HOST_PORT=5000
    - WEB_GUEST_PORT=5000
    - WEB_HOST_SECURE_PORT=8443
    - WEB_GUEST_SECURE_PORT=8443

install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
- sudo apt-get install -y libmysqlclient-dev chromium-chromedriver
- pip install -r tests/requirements-test.txt

before_script:
- sudo scripts/bootstrap.sh $ENVIRONMENT $BASE_FOLDER
- openssl req -x509 -newkey rsa:4096 -nodes -out web_s2i/cert.pem -keyout web_s2i/key.pem -days 365 -subj "/C=IL/ST=Gush-Dan/L=Tel-Aviv/O=DevOps Loft/OU=''/CN=''"
- scripts/docker-compose-provision.sh $ENVIRONMENT $BASE_FOLDER $WEB_HOST_PORT $WEB_GUEST_PORT $WEB_HOST_SECURE_PORT $WEB_GUEST_SECURE_PORT

script:
- tests/basic_http_get_test.py
- tests/navbar.py
- tests/test_vault.py
- tests/wait_mysql_up.sh
- sleep 15
- tests/is_table_empty.py
- flake8 --exclude venv .
