version: "3.7"
services:
  db:
    image: $APP/db
    build: ./db_s2i
    container_name: db
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - /tmp/.devopsloft:/tmp/.devopsloft
    restart: always

  app:
    image: $APP/app
    build: ./app_s2i
    container_name: app
    environment:
      - STATCODES
      - ENVIRONMENT
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - APP_GUEST_PORT
      - PYTHONPATH=$$PYTHONPATH:/modules
      - VAULT_ADDR=http://vault:$VAULT_GUEST_PORT
    ports:
      - $APP_HOST_PORT:$APP_GUEST_PORT
    volumes:
      - $BASE_FOLDER/modules:/modules
      - /tmp/.devopsloft:/tmp/.devopsloft
    restart: always

  vault:
    image: $APP/vault
    container_name: vault
    build:
      context: ./vault_s2i
      args:
        VAULT_GUEST_PORT: ${VAULT_GUEST_PORT}
    ports:
      - $VAULT_HOST_PORT:$VAULT_GUEST_PORT
    cap_add:
      - IPC_LOCK
    command: server
    volumes:
      - /tmp/.devopsloft:/tmp/.devopsloft
    restart: always

  web:
    image: $APP/web
    build:
      context: ./web_s2i
    container_name: web
    ports:
      - $WEB_HOST_PORT:$WEB_GUEST_PORT
      - $WEB_HOST_SECURE_PORT:$WEB_GUEST_SECURE_PORT
    volumes:
      - /tmp/.devopsloft:/tmp/.devopsloft
    restart: always
