version: "3"
services:
  db:
    image: ${NAMESPACE:-devopsloft}/db
    build: 
      context: .
      dockerfile: db_s2i/Dockerfile
    container_name: db
    environment:
      - SERVICE_NAME=db
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - 3306:3306
    restart: always

  app:
    image: ${NAMESPACE:-devopsloft}/app
    build:
      context: .
      dockerfile: app_s2i/Dockerfile
      args:
        - ENVIRONMENT
        - APP_GUEST_PORT
    container_name: app
    environment:
      - SERVICE_NAME=app
      - PYTHONPATH=$$PYTHONPATH:/modules
    ports:
      - 3000:3000
    links:
      - db
    restart: always

  vault:
    image: ${NAMESPACE:-devopsloft}/vault
    build:
      context: .
      dockerfile: vault/Dockerfile
    container_name: vault
    environment:
      - SERVICE_NAME=vault
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  web:
    image: ${NAMESPACE:-devopsloft}/web
    build:
      context: .
      dockerfile: web_s2i/Dockerfile
      args:
        WEB_HOST_PORT: ${WEB_HOST_PORT}
        WEB_HOST_SECURE_PORT: 8443
        APP_HOST_PORT: 3000
    container_name: web
    environment:
      - SERVICE_NAME=web
    ports:
      - ${WEB_HOST_PORT}:${WEB_HOST_PORT}
      - 8443:8443
    links:
      - app
    restart: always
